Repository HUFS-9oormthonuniv-4th/Chulcheck-Frontend, pull requests merged in 2025-06, with the labels that each got.

#5 refactor: auth 컴포넌트 및 로직 분리, layout padding 추가, 그외 불필요한 페이지 archive 이동
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  src/app/auth/basic-edit/page.tsx
  src/app/auth/basic-info/page.tsx
  src/app/auth/components/BasicInfoForm.tsx
  src/app/auth/components/ErrorAlert.tsx
  src/app/auth/components/LoginForm.tsx
  src/app/auth/components/SignupForm.tsx
  src/app/auth/components/SocialLogin/GoogleLoginButton.tsx
  src/app/auth/components/SocialLogin/KakaoLoginButton.tsx
  src/app/auth/components/SocialLogin/NaverLoginButton.tsx
  src/app/auth/components/SocialLogin/SocialLoginButtons.tsx
  src/app/auth/components/VerifyEmailForm.tsx
  src/app/auth/hooks/useBasicInfoForm.ts
  src/app/auth/hooks/useLoginForm.ts
  src/app/auth/hooks/useSignupForm.ts
  src/app/auth/hooks/useVerifyEmailForm.ts
  src/app/auth/login/page.tsx
  src/app/auth/reset-password/page.tsx
  src/app/auth/signup/page.tsx
  src/app/auth/verify-email/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/archive/basic-edit/EditProfileForm.tsx
  src/archive/basic-edit/page.tsx
  src/archive/basic-edit/useEditProfileForm.ts
  src/archive/reset-password/ResetPasswordForm.tsx
  src/archive/reset-password/page.tsx
  src/archive/reset-password/useResetPasswordForm.ts
  src/assets/logo_wordmark.svg
  src/components/svg/logo_wordmark.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/separator.tsx
  src/components/ui/skeleton.tsx
  src/lib/type/svg.d.ts
  src/lib/utils/utils.ts
  src/validation/auth-validation.ts
  tsconfig.json
Labels: Type: Refactor

#6 feat(admin): 관리자(내동아리상세, 설정, 수정, 삭제)페이지 UI퍼블리싱
  package-lock.json
  package.json
  src/app/admin/components/Button.tsx
  src/app/admin/components/admin-main/AttendanceGraph.tsx
  src/app/admin/components/admin-main/AttendanceList.tsx
  src/app/admin/components/admin-main/CopyLink.tsx
  src/app/admin/components/admin-main/InfoBox.tsx
  src/app/admin/components/admin-main/InfoGrid.tsx
  src/app/admin/components/admin-main/ManageTabs.tsx
  src/app/admin/components/admin-main/MemberList.tsx
  src/app/admin/components/admin-main/MemberListSelect.tsx
  src/app/admin/components/setting/FormField.tsx
  src/app/admin/page.tsx
  src/app/admin/setting/delete-club/page.tsx
  src/app/admin/setting/edit-club/page.tsx
  src/app/admin/setting/page.tsx
  src/assets/logo_wordmark.svg
  src/components/svg/logo_wordmark.tsx
  src/components/ui/Header.tsx
  src/lib/type/admin.ts
  src/mocks/admin.ts
Labels: Type:UI

#7 feat(club): 동아리 생성 페이지 UI 퍼블리싱
  src/app/(main)/clubs/components/CreateClubForm.tsx
  src/app/(main)/clubs/create/page.tsx
  src/assets/icons/folder-plus.svg
  src/components/ui/textarea.tsx
Labels: Type:UI

#12 feat(club): 동아리 참여하기 페이지 UI 퍼블리싱
  src/app/(main)/clubs/components/TabCard.tsx
  src/app/(main)/clubs/components/join/BottomSheet.tsx
  src/app/(main)/clubs/components/join/EmptyClub.tsx
  src/app/(main)/clubs/components/join/PasteLink.tsx
  src/app/(main)/clubs/join/page.tsx
  src/app/(main)/clubs/page.tsx
  src/components/ui/TitleAndDescription.tsx
Labels: Type:UI

#10 feat(main) : 출석체크, 최근 출석기록, 뱃지 ui 구현 완료
  package-lock.json
  package.json
  public/QRbackgroundImg.jpg
  public/assets/badge/master-off.svg
  public/assets/badge/master-on.svg
  public/assets/badge/new-member-off.svg
  public/assets/badge/new-member-on.svg
  public/assets/badge/owner-off.svg
  public/assets/badge/owner-on.svg
  public/assets/badge/perfect-attendance-award-off .svg
  public/assets/badge/perfect-attendance-award-on .svg
  public/assets/badge/pro-off.svg
  public/assets/badge/pro-on.svg
  public/assets/badge/rain-off.svg
  public/assets/badge/rain-on.svg
  public/assets/badge/regular-attendance-king-off.svg
  public/assets/badge/regular-attendance-king-on.svg
  public/assets/badge/states/fail-badge.svg
  public/assets/badge/states/late-badge.svg
  public/assets/badge/states/success-badge.svg
  src/app/(attendance)/check/AttendancdCheckSystemModal.tsx
  src/app/(attendance)/check/AttendancePinInput.tsx
  src/app/(attendance)/check/AttendanceQrScan.tsx
  src/app/(attendance)/check/QrCard.tsx
  src/app/(main)/clubs/[clubId]/page.tsx
  src/app/(main)/clubs/components/detail/MemberList.tsx
  src/app/(main)/clubs/components/join/BottomSheet.tsx
  src/app/(main)/clubs/join/page.tsx
  src/app/(main)/clubs/page.tsx
  src/app/(main)/component/AttendanceBadge.tsx
  src/app/(main)/component/AttendanceLogCard.tsx
  src/app/(main)/component/AttendanceLogMain.tsx
  src/app/(main)/component/AttendanceMain.tsx
  src/app/(main)/page.tsx
  src/app/auth/(routes)/signup/page.tsx
  src/app/auth/(routes)/verify-email/page.tsx
  src/app/auth/basic-edit/page.tsx
  src/app/auth/components/BasicInfoForm.tsx
  src/app/my-badges/page.tsx
  src/app/page.tsx
  src/archive/basic-edit/EditProfileForm.tsx
  src/archive/reset-password/page.tsx
  src/components/TitleAndDescription.tsx
Labels: Type:UI

#15 feat: 대기중UI 퍼블리싱, 카카오 로그인 연결, 바텀시트 css 수정
  src/app/(attendance)/check/AttendancdCheckSystemModal.tsx
  src/app/(main)/clubs/[clubId]/page.tsx
  src/app/(main)/clubs/join/page.tsx
  src/app/(main)/clubs/page.tsx
  src/app/(main)/page.tsx
  src/app/admin/attendance/[id]/page.tsx
  src/app/admin/components/AttendanceBottomSheet.tsx
  src/app/admin/components/BottomSheetWrapper.tsx
  src/app/admin/components/setting/ApprovalBottomSheet.tsx
  src/app/admin/create-session/check-attendance/page.tsx
  src/app/admin/create-session/check-qr/page.tsx
  src/app/admin/member/[memberId]/page.tsx
  src/app/admin/page.tsx
  src/app/admin/setting/approval/page.tsx
  src/app/admin/setting/delete-club/page.tsx
  src/app/admin/setting/edit-club/page.tsx
  src/app/admin/setting/page.tsx
  src/app/auth/(routes)/login/page.tsx
  src/app/auth/components/SocialLogin/KakaoLoginButton.tsx
  src/app/layout.tsx
  src/components/TitleAndDescription.tsx
  src/components/ui/Header.tsx
  src/mocks/admin.ts
Labels: Type:UI, Type: Feature

#17 feat(demo): 관리자 데모 더미데이터 세팅
  public/qr.jpg
  src/app/(main)/clubs/[clubId]/page.tsx
  src/app/(main)/clubs/check-attendance/page.tsx
  src/app/(main)/clubs/components/detail/ManageMyAttendance.tsx
  src/app/admin/attendance/[id]/page.tsx
  src/app/admin/components/AttendanceBottomSheet.tsx
  src/app/admin/components/admin-main/AttendanceList.tsx
  src/app/admin/components/admin-main/CopyLink.tsx
  src/app/admin/components/admin-main/InfoGrid.tsx
  src/app/admin/components/admin-main/MemberList.tsx
  src/app/admin/components/attendance/AttendanceInfo.tsx
  src/app/admin/create-session/check-attendance/page.tsx
  src/app/admin/create-session/check-qr/page.tsx
  src/app/admin/member/[memberId]/page.tsx
  src/app/admin/page.tsx
  src/app/admin/setting/approval/page.tsx
  src/components/ui/Header.tsx
  src/mocks/admin/admin.ts
  src/mocks/admin/dummy-members.ts
  src/mocks/member.ts
Labels: Type:UI

#19 Fix/demo admin
  src/app/(main)/clubs/components/detail/AttendanceCard.tsx
  src/app/(main)/clubs/components/detail/ManageMyAttendance.tsx
  src/app/(main)/clubs/components/detail/MemberList.tsx
  src/app/(main)/clubs/create/page.tsx
  src/app/(main)/clubs/join/page.tsx
  src/app/(main)/clubs/page.tsx
  src/app/(main)/component/AttendanceMain.tsx
  src/app/(main)/page.tsx
  src/app/admin/create-session/check-attendance/page.tsx
  src/components/ui/Header.tsx
Labels: Type:UI, Type: BugFix
